ViewComponents/UserDetailViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using MyBlog.Models;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace MyBlog.ViewComponents
{
    public class UserDetailViewComponent : ViewComponent
    {
        private readonly MyBlogDbContext _context;

        public UserDetailViewComponent(MyBlogDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            string id = HttpContext.User.FindFirstValue(ClaimTypes.Sid);

            var acc = await _context.Users.FirstOrDefaultAsync(a => a.UserId == id);

            if (acc != null)
            {
                return View(acc);
            }

            return View(new Users { UserId = "0"});
        }
    }
}

Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Blog - @ViewData["PageName"]</title>
    <!-- Custom fonts for this template-->
    <link href="~/lib/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/lib/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <li>
                <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-action="Index" asp-controller="Admin">
                    <div class="sidebar-brand-text mx-3">Admin</div>
                </a>
            </li>
            <!-- Divider -->
            <li>
                <hr class="sidebar-divider my-0">
            </li>
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Admin">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Màn hình chính</span>
                </a>
            </li>
            <!-- Divider -->
            <li>
                <hr class="sidebar-divider">
            </li>
            <!-- Heading -->
            <li>
                <div class="sidebar-heading">
                    Interface
                </div>
            </li>
            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
            </li>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <li class="topbar-divider d-none d-sm-block"></li>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            @await Component.InvokeAsync("UserDetail")
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-action="Logout" asp-controller="Admin">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Đăng xuất
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of topbar -->

                <!-- Main content -->
                @RenderBody()
                <!-- End of main content -->
            </div>
        </div>
        <!-- End of content wrapper -->
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/lib/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/lib/js/sb-admin-2.min.js"></script>
    <!-- Page level plugins -->
    <script src="~/lib/vendor/chart.js/Chart.min.js"></script>
    <!-- Page level custom scripts -->
    <script src="~/lib/js/demo/chart-area-demo.js"></script>
    <script src="~/lib/js/demo/chart-pie-demo.js"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Blog - @ViewData["PageName"]</title>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CMuli:400,700" rel="stylesheet" />
    <link type="text/css" rel="stylesheet" href="~/lib/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/css/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="~/lib/css/style.css" />
</head>
<body>
    <header id="header">
        <div id="nav">
            <div id="nav-top">
                <div class="container">
                    <ul class="nav-social">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                    </ul>

                    <div class="nav-logo">
                        <a asp-action="Index" asp-controller="Home" class="logo"><img src="~/images/blogger-logo.jpg"></a>
                    </div>

                    <div class="nav-btns">
                        <button class="aside-btn"><i class="fa fa-bars"></i></button>
                        <button class="search-btn"><i class="fa fa-search"></i></button>
                        <div id="nav-search">
                            <form>
                                <input class="input" name="search" placeholder="Tìm kiếm câu chuyện...">
                            </form>
                            <button class="nav-close search-close">
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div id="nav-bottom">
                <div class="container">
                    <ul class="nav-menu">
                        <li><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                        <li class="has-dropdown">
                            <a href="#">Danh mục</a>
                        </li>
                        <li><a href="#">Câu truyện</a></li>
                        <li><a href="#">Chủ Blog</a></li>
                    </ul>
                </div>
            </div>

            <div id="nav-aside">
                <ul class="nav-aside-menu">
                    <li><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                    <li class="has-dropdown">
                        <a href="#">Danh mục</a>
                    </li>
                    <li><a href="#">Câu chuyện</a></li>
                    <li><a asp-action="About" asp-controller="Home">Chủ Blog</a></li>
                    <li><a href="#">Liên hệ quảng cáo</a></li>
                </ul>
                <button class="nav-close nav-aside-close"><span></span></button>
            </div>
        </div>
    </header>

    @RenderBody()

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="footer-widget">
                        <div class="footer-logo">
                            <a asp-action="Index" asp-controller="Home" class="logo"><img src="~/images/blogger-logo.jpg"></a>
                        </div>
                        <ul class="contact-social">
                            <li><a href="#" class="social-facebook"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="social-twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="social-google-plus"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#" class="social-instagram"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="footer-bottom row">
                <div class="col-md-6 col-md-push-6">
                    <ul class="footer-nav">
                        <li><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                        <li><a asp-action="About" asp-controller="Home">Chủ Blog</a></li>
                        <li><a asp-action="" asp-controller="Home">Liên hệ quảng cáo</a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-md-pull-6">
                    <div class="footer-copyright">
                        Copyright ©
                        <script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/js/bootstrap.min.js"></script>
    <script src="~/lib/js/jquery.min.js"></script>
    <script src="~/lib/js/jquery.stellar.min.js"></script>
    <script src="~/lib/js/main.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
</body>
</html>